CREATE TABLE IF NOT EXISTS refresh_tokens(
    id BIGSERIAL    PRIMARY KEY,
    token           VARCHAR(255) NOT NULL,
    user_id BIGINT  NOT NULL UNIQUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);