spring.application.name=moldunity

spring.config.import = env.properties

# Data / JPA
spring.jpa.hibernate.ddl-auto = update
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.jpa.show-sql = true


# Servlet
server.servlet.session.cookie.http-only = true
server.servlet.session.cookie.secure = true
server.servlet.session.timeout = 7d

# Email
email.username = ${EMAIL_USERNAME}
email.password = ${EMAIL_PASSWORD}
email.host = ${EMAIL_HOST}


spring.threads.virtual.enabled=true