spring.application.name=moldunity

spring.config.import = env.properties

# Data / JPA
spring.jpa.hibernate.ddl-auto = update
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.jpa.show-sql = true
spring.jpa.open-in-view=false


# MongoDB Configuration
spring.data.mongodb.uri= mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/moldunity
spring.data.mongodb.database=moldunity
spring.data.mongodb.auto-index-creation=true


# Servlet
server.servlet.session.cookie.http-only = true
server.servlet.session.cookie.secure = true
server.servlet.session.timeout = 7d

# Email
email.username = ${EMAIL_USERNAME}
email.password = ${EMAIL_PASSWORD}
email.host = ${EMAIL_HOST}

spring.threads.virtual.enabled=true

articles.limit = 5
